#!/bin/bash
#echo "updating system"
#sudo apt-get update
#echo "done"


#echo "installing NodeJS's latest version"
#curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
#sudo apt-get install -y nodejs
#echo "done"

echo "installing packages.json packages"
cp -R PNSMN/ /root
cd /root/PNSMN
npm install
echo "done"

echo "installation complete"
echo "                                                   "
echo "                                      PNSMNPNSM     "                                    
echo "                                  NPNSMNPNSMNPNSMNP  "                                   
echo "                              NSMNPNSMNPNSMNPNSMNPNSMN                                "  
echo "                      PNSMNPNSMNPNSMN           PNSMNPNS                                "
echo "                   MNPNSMNPNSMNP                  NSMNPNS                               "
echo "                 MNPNSMNPNSMNPNS                   MNPNSM                               "
echo "                 NPNSMNPNSMNPNSMN                   PNSMN                               "
echo "                 PNSMNPNSMNP NSMNPN    SMNPNSMNPNS  MNPNS                               "
echo "                 MNPNSMNPNSMNPNSMNPN SMNPNSMNPNSMNPN SMNP                               "
echo "                 NSMNPNSMNPNSMNPNS  MNPNSMNPNSMNPNSMNPNSM                               "
echo "                NPNSM  NPNSMNPNSMN  PNSMNPNSMNPNSMNPNSMNP                               "
echo "               NSMNPNSMNPNSMNPNSMNP NSMNPNSMNPN SMNPNSMNP                               "
echo "              NSMNPNSMNPNSMNPNSMN   PNSMNPNSMNPNSMNPNSMNP                               "
echo "             NSMNPNSMNPNSMNPNSMNPNSMNPNSMNPNSMNPN  SMNPN                                "
echo "            SMNPN          SMNPNSMNPNSMNPNSMN     PNSMNP                                "
echo "           NSMNP                      NSMNPNS     MNPNSM                                "
echo "          NPNSMN                                 PNSMNP                                 "
echo "         NSMNPN                                 SMNPNS                                  "
echo "        MNPNSM                                  NPNSMN                                  "
echo "        PNSMN                      PNSM        NPNSMN                                   "
echo "        PNSM                      NPNSM NPN   SMNPNS                                    "
echo "        MNPN                      SMNPNSMNPN  SMNPN                         SMNPNSMNP   "
echo "       NSMNP                      NSMNPNSMN  PNSMN                        PNSMNPNSMNPN  "
echo "       SMNPN                     SMNPNSMNPN SMNPN                       SMNPNS    MNPN  "
echo "       SMNPN                     SMNPNSMNP  NSMNP                     NSMNPNS    MNPNS  "
echo "       MNPNS                    MNPNSMNPN  SMNPNS                   MNPNSMN     PNSMN   "
echo "       PNSMN                    PNSMNPNS   MNPNSMNPNSMNPNSMNPNS   MNPNSMN     PNSMN     "
echo "        PNSM                   NPNSMNPN    SMNPNSMNPNSMNPNSMNPNSMNPNSMN      PNSMN      "
echo "        PNSM                   NPNSMNP     NSMNP   NSMNP   NSMNPNSMNP      NSMNPN       "
echo "        SMNP                  NSMNPNSM      NPN   SMNPNSMNPNSMNPNSM      NPNSMN         "
echo "        PNSMN               PNSMN PNSMN         PNSMNPNSMNPNSMNPNS     MNPNSMN          "
echo "         PNSM             NPNSM  NPNSMNP         NSMNPNSMNPNSMNPNSMN   PNSMNPNS        " 
echo "         MNPNS            MNPNSMNPNSMNPN                     SMNPNSMN    PNSMNPNSM    "  
echo "          NPNSM            NPNSMNPNSMNP              NSMN       PNSMNP  NSMN PNSMN   "   
echo "          PNSMNP              NSMN                   PNSM        NPNSMN  PNSMNPNS   "    
echo "           MNPNSM                                NPN              SMNPN    SMNP    "     
echo "            NSMNPNSM                            NPNS              MNPNS     MNPN  "      
echo "               SMNPNSM                          NPNS              MNPNSMNPNSMNPN "       
echo "     SMN        PNSMNPNSMN                       PNSM           NPNSMNPNSMNPNSM "        
echo "    NPNSMNP    NSMNPNSMNPNSMNPNS                  MNP         NSMNPNS    M     "         
echo "    NPNSMNPNSMNPNS MNPNSMNPNSMNPNSMNPNSM           NPNS    MNPNSMN            "          
echo "    PNSM NPNSMNPNSMNPNS    MNPNSMNPNSMNPNS MNPNSMNPNSMNPNSMNPNSM            "            
echo "     NPNS  MNPNSMNPNS         MNPNSMNPNSM NPNSMNPNSMNPNSMNPNS                "           
echo "      MNPN   SMNPNS         MNPNSMNPNSMN PNSMN PNSMNPNSMNP                "              
echo "       NSMNPNSMNP           NSMNPNSMNPN  SMNP                            "               
echo "        NSMNPNS              MNPNSMNP   NSMN                            "                
echo "          PNS                MNPNSM    NPNS                            "                 
echo "                              MNPNSM  NPNS                            "                  
echo "                               MNPNSMNPNS         "                                      
echo "                                 MNPNSMN         "                                       
echo "                                   PNS          "